export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCHING_TEAMS_SUCCESS = 'FETCHING_TEAMS_SUCCESS';
export const FETCHING_TEAMS_FAILURE = 'FETCHING_TEAMS_FAILURE';

export const FETCHING_LEADERBOARD_TEAMS = 'FETCHING_LEADERBOARD_TEAMS';
export const FETCHING_LEADERBOARD_TEAMS_SUCCESS =
  'FETCHING_LEADERBOARD_TEAMS_SUCCESS';
export const FETCHING_LEADERBOARD_TEAMS_FAILURE =
  'FETCHING_LEADERBOARD_TEAMS_FAILURE';

export const FETCHING_QUIZ = 'FETCHING_QUIZ';
export const FETCHING_QUIZ_SUCCESS = 'FETCHING_QUIZ_SUCCESS';
export const FETCHING_QUIZ_FAILURE = 'FETCHING_QUIZ_FAILURE';

export const FETCHING_QUIZZES = 'FETCHING_QUIZZES';
export const FETCHING_QUIZZES_SUCCESS = 'FETCHING_QUIZZES_SUCCESS';
export const FETCHING_QUIZZES_FAILURE = 'FETCHING_QUIZZES_FAILURE';
