export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCHING_TEAMS_SUCCESS = 'FETCHING_TEAMS_SUCCESS';
export const FETCHING_TEAMS_FAILURE = 'FETCHING_TEAMS_FAILURE';

export const FETCHING_LEADERBOARD_TEAMS = 'FETCHING_LEADERBOARD_TEAMS';
export const FETCHING_LEADERBOARD_TEAMS_SUCCESS =
  'FETCHING_LEADERBOARD_TEAMS_SUCCESS';
export const FETCHING_LEADERBOARD_TEAMS_FAILURE =
  'FETCHING_LEADERBOARD_TEAMS_FAILURE';
